repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.4.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: detect-private-key
      - id: check-ast
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.261'
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
      - id: black